version: '3'

services:
  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
    volumes:
      - opensearch-data:/usr/share/opensearch/data 
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=https://opensearch-node:9200
    ports:
      - 5601:5601

volumes:
  opensearch-data:
